### ISSUE TITLE
NWC does not work and webln issues

### ISSUE THREAD

**Issue by rolznz** [verbiricha/habla.news#112]
- Bitcoin connect is only imported if webln already exists, this is never true on mobile - see https://github.com/verbiricha/habla.news/blob/main/src/hooks/useWebln.js#L10 - I see there is an issue with SSR and it breaking because `window` does not exist. I'll have a look.
- `webln.enabled` is checked at https://github.com/verbiricha/habla.news/blob/main/src/components/ZapModal.tsx - `enabled` is an internal variable (and does not exist on some webln instances, like bitcoin connect NWC). The ~~standard~~recommended method is to try to await webln.enable(), and if it fails (an exception is thrown) then use the fallback QR / open wallet approach.
- Typings could be added with https://www.npmjs.com/package/@webbtc/webln-types

Reference: https://webln.guide/

**Comment by nicky-dev** [comment]
I got this error in iOS PWA

<img src="https://github.com/verbiricha/habla.news/assets/14047941/b0c09c65-a50a-4578-b5bd-b2caa1c2971b" alt="IMG_2110" width="200"/>

**Comment by rolznz** [comment]
@nicky-dev what iOS version are you using?

**Comment by nicky-dev** [comment]
> @nicky-dev what iOS version are you using?

iOS Version: 16.7

**Comment by rolznz** [comment]
Hmm. It works fine for me on 16.3.1. That is just when you connected to your wallet, right?

I'll create an issue and let you know if I can reproduce it or find a fix.

**Comment by rolznz** [comment]
@nicky-dev does it also happen when you access the site from Safari rather than with the PWA?

**Comment by nicky-dev** [comment]
It happens when using the PWA.

**Comment by rolznz** [comment]
@nicky-dev did you install the PWA from a secure HTTPS context? like a ngrok https:// URL?

I have the same issue when I save the PWA for http://localhost:3000

**Comment by rolznz** [comment]
I made a PR for the fixes here: https://github.com/verbiricha/habla.news/pull/114

**Comment by nicky-dev** [comment]
> @nicky-dev did you install the PWA from a secure HTTPS context? like a ngrok https:// URL?
> 
> I have the same issue when I save the PWA for http://localhost:3000 (on iOS. On desktop it works fine)

Thanks @rolznz,  It work from ngrok https.
