### ISSUE TITLE
Habla removes non standard tags on edit

### ISSUE THREAD

**Issue by basantagoswami** [verbiricha/habla.news#145]
We are working on a [project](https://gitlab.com/walletscrutiny/nostr-opinion-plugin) that utilizes long form content events, and we are adding a non standard tag called "sentiment" to our events for our own purpose. But once the events are edited from habla they get removed from the events.

The desired behaviour should be that clients [don't make changes to unknown data](https://github.com/Giszmo/nips/blob/protectTheUnknown/24.md).

Habla is changing the alt tag to it's default one as well, which probably should not be done either.

**Comment by verbiricha** [comment]
Thanks for reporting Basanta, this is a bug in Habla!

**Comment by verbiricha** [comment]
Have fixed this in the last release of Habla, let me know if you find more issues!
