### ISSUE TITLE
Post lost randomly

### ISSUE THREAD

**Issue by Giszmo** [verbiricha/habla.news#146]
I was writing a lengthy post, went to have lunch and when I came back, the post was gone. The tab was still open. Nobody else used the PC. It was just gone.

While #138 might help recover from this, I think it's an independent bug that should be tracked down. I have no idea what could have triggered this.

**Comment by verbiricha** [comment]
This is really bad, do you have any more information? Perhaps console logs?

**Comment by Giszmo** [comment]
No. As I said I have no more information. As far as I'm concerned, we can close this issue and hope it was me/my daughter hitting delete without noticing. If others experience the same, we can open it again.
