### ISSUE TITLE
Screen does not change when accessing habla article from within habla article

### ISSUE THREAD

**Issue by Lokuyow** [verbiricha/habla.news#155]
**To Reproduce**
1. Access this habla article. https://habla.news/ja/u/lokuyow.github.io/1707912490439
2. Jump to habla article from link. [Nostrのカスタム絵文字の使い方](https://habla.news/ja/u/lokuyow.github.io/xVMTZxHcV_NWKuTbDBUYs)
3. The screen does not change and I cannot jump to the article. (It will display correctly if you press the refresh button on your browser.)

**Device**
 - Windows 11
 - Google Chrome 121.0.6167.185

**Comment by verbiricha** [comment]
Thanks for the heads up, will fix!

**Comment by verbiricha** [comment]
Fixed, will be deployed in the next few minutes.

**Comment by Lokuyow** [comment]
Thank you very much!
