### ISSUE TITLE
"Your comment was not published to all relays" without hint as to how many relays accepted the event

### ISSUE THREAD

**Issue by Giszmo** [verbiricha/habla.news#160]
I have many relays configured in my profile and some are bad sometimes, so I always get this "Error: Warning: ..." but Habla doesn't tell me if it completely failed or only partially. Please at least show a counter. "Event published to 10 of 12 relays" without "error" or "warning" as this is sort of expected. "1 of 12" might be worthy a "warning" and "0 of 12" an error.

**Comment by verbiricha** [comment]
We use [zapthreads](https://github.com/fr4nzap/zapthreads) for comments.

**Comment by Giszmo** [comment]
Sorry but pointing blame doesn't justify closing the issue. It's still an issue in this project until the library fixes the issue which I can't even find an issue for this.

**Comment by fr4nzap** [comment]
I will take care of this
