### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by verbiricha** [verbiricha/habla.news#24]
- [ ] Setting up (profile)
- [ ] Discover (hashtags and people)
Advanced (after initial onboarding)
- [ ] Keys
- [ ] Relays

**Comment by jbasallaje** [comment]
Latest flow from @gzuuus w/ the minimal onboarding version: [figma](https://www.figma.com/file/I5LXiZwRl73gg2SH9HOSDh/Onboarding-experience?type=design&node-id=1%3A17&mode=design&t=cb5VTCvh7thIBeg4-1)
