### ISSUE TITLE
Warning pop-up before leaving writing page with text

### ISSUE THREAD

**Issue by armstrys** [verbiricha/habla.news#32]
I have had a few times where I have accidentally navigated away from the "write post" page while I am constructing text. It would be really helpful to have a warning box pop-up to make sure that the user wants to leave the page. Those alerts can be annoying in some circumstances, but definitely not as annoying as accidentally swiping incorrectly on your mousepad and losing a bunch of text!

**Comment by jbasallaje** [comment]
@verbiricha, my first thought is that this could be a default Chrome modal that shows up conditionally if there's text in the editor. But, if there's a need for a more custom modal, I can begin to mock one up.

Ex: tdraft.io (I'd change copy here to "Leave page" or "Leave editor")
![image](https://github.com/verbiricha/habla.news/assets/56495918/4d7d3211-096d-47b8-9faa-2540ef068cb9)

**Comment by verbiricha** [comment]
>my first thought is that this could be a default Chrome modal that shows up conditionally if there's text in the editor.

let's do this!

**Comment by verbiricha** [comment]
Not showing a warning to not annoy users but your current post will be saved in local storage now. If you navigate away or close the tab you can still return to the write interface and continue where you left.
