### ISSUE TITLE
NIP 47

### ISSUE THREAD

**Issue by verbiricha** [verbiricha/habla.news#96]
https://github.com/getAlby/bitcoin-connect

**Comment by nicky-dev** [comment]
Should we replace `Lightning Address Form` with `BitcoinConnectButton` ?
![image](https://github.com/verbiricha/habla.news/assets/14047941/f4fac003-6fd4-4d91-8eff-1a86fb418caf)

**Comment by verbiricha** [comment]
Probably worth keeping it so users can still see and edit their ln address, wdyt?

**Comment by nicky-dev** [comment]
OK

**Comment by nicky-dev** [comment]
I have created a PR for this issue. Please take a look.

If you have any suggestions for improving the UI, please let me know.
